### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bitplus** [rumsystem/quorum#25]
2021-11-10T09:59:55.717+0800    DEBUG   user    chain/molassesuser.go:61        <3bb7a3be-d145-44af-94cf-e64b992ff8f0> AddBlock called
2021-11-10T09:59:55.716+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAmBigME5YdVJxfvp8GxU3DacFjvZT9LUDu19erGsyYw8Sq: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAm7wwBcznVF2jpyKkJ4ssGjGqStMjtuWXGueXgVuMTnLYG: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAkywzUsPZ1yHZxV18ZPL5NosXyCWvErWuaWUmpzp9TCvtG: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAmBigME5YdVJxfvp8GxU3DacFjvZT9LUDu19erGsyYw8Sq: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAmQBz6JHhma4oXRAwR7dQLLH6S2HrzH9Kci4Mbk1DA2SRL: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAmVFGwfgrXLNXyTY9SjFAFQ6jhyzUZBnkfar2D7kp6f27d: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAmVX7uWuLXwgdNmPARsSVfuZcQyv3ZVPxuqeXceA5NaXu8: queue
full
2021-11-10T09:59:55.719+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:1144       dropping message to peer 16Uiu2HAm8RKsPhxVDsu8MGL8ZxrhyyfZesfX5C9ohx3aDgMYdGJx: queuefull
2021-11-10T09:59:55.722+0800    DEBUG   user    chain/molassesuser.go:201       <3bb7a3be-d145-44af-94cf-e64b992ff8f0> applyTrxs called2021-11-10T09:59:55.722+0800    DEBUG   user    chain/molassesuser.go:245       <3bb7a3be-d145-44af-94cf-e64b992ff8f0> try apply trx <7ad58af6-c260-4318-b966-6f05c6ad3405>
2021-11-10T09:59:55.722+0800    DEBUG   user    chain/molassesuser.go:249       <3bb7a3be-d145-44af-94cf-e64b992ff8f0> apply POST trx
2021-11-10T09:59:55.723+0800    INFO    dbmgr   storage/dbmgr.go:397    Add POST with key default_grp_cnt_3bb7a3be-d145-44af-94cf-e64b992ff8f0_1634717703348800900_7ad58af6-c260-4318-b966-6f05c6ad3405
2021-11-10T09:59:55.723+0800    DEBUG   user    chain/molassesuser.go:135       <3bb7a3be-d145-44af-94cf-e64b992ff8f0> move block <72b83ae0-39cd-4196-bf2d-c2fbc67c7283> from cache to chain
2021-11-10T09:59:55.725+0800    DEBUG   user    chain/molassesuser.go:156       <3bb7a3be-d145-44af-94cf-e64b992ff8f0> height before recal <65>2021-11-10T09:59:55.725+0800    DEBUG   user    chain/molassesuser.go:165       <3bb7a3be-d145-44af-94cf-e64b992ff8f0> new height <66>, new highest blockId 72b83ae0-39cd-4196-bf2d-c2fbc67c7283
2021-11-10T09:59:55.725+0800    DEBUG   chain   chain/chain.go:144      <3bb7a3be-d145-44af-94cf-e64b992ff8f0> UpdChainInfo called
2021-11-10T09:59:55.725+0800    INFO    chain   chain/chain.go:148      <3bb7a3be-d145-44af-94cf-e64b992ff8f0> Chain Info updated 66, 72b83ae0-39cd-4196-bf2d-c2fbc67c7283
2021-11-10T09:59:55.725+0800    DEBUG   pubsub  go-libp2p-pubsub@v0.5.4/gossipsub.go:660        IHAVE: Asking for 698 out of 698 messages from 16Uiu2HAm6S4fFgrL1EvwtrcMznDssQTBpzWMHzhhG8dEunVzVosL
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x102079f]

goroutine 629 [running]:
github.com/rumsystem/quorum/internal/pkg/chain.(*Syncer).AddBlockSynced(0xc015734500, 0xc00ace75f0, 0xc0058bc1a0, 0x34, 0xc0155c9b58)
        C:/Users/samso/go/src/quorum/internal/pkg/chain/syncer.go:167 +0x6ff
github.com/rumsystem/quorum/internal/pkg/chain.(*Chain).handleReqBlockResp(0xc0157365a0, 0xc0049b26c0, 0x34, 0x6af500)
        C:/Users/samso/go/src/quorum/internal/pkg/chain/chain.go:294 +0x4ec
github.com/rumsystem/quorum/internal/pkg/chain.(*Chain).HandleTrx(0xc0157365a0, 0xc0049b26c0, 0xa000, 0x16bd500)
        C:/Users/samso/go/src/quorum/internal/pkg/chain/chain.go:183 +0x449
github.com/rumsystem/quorum/internal/pkg/pubsubconn.(*P2pPubSubConn).handleGroupChannel(0xc013ef5e60, 0x13, 0xc01185f310)
        C:/Users/samso/go/src/quorum/internal/pkg/pubsubconn/p2p_pubsubconn.go:87 +0x1ce
created by github.com/rumsystem/quorum/internal/pkg/pubsubconn.(*P2pPubSubConn).JoinChannel
        C:/Users/samso/go/src/quorum/internal/pkg/pubsubconn/p2p_pubsubconn.go:51 +0x3ea

**Comment by bitplus** [comment]
It seems had been fixed from new commits.
